### ISSUE TITLE
Confusing rule name "reanalyse: subject wh"

### ISSUE THREAD

**Issue by snoions** [abrsvn/pyactr-book#3]
Correctly me if I wrong - in pyactr-book/book-code/ch7_grodner_gibson/parser_rules.py the purpose of the rule "reanalyse: subject wh" is to revise the initial prediction of subject gapping to a prediction of object gapping.  Wouldn't "reanalyse: object wh" be a better name in that case?  It confused me when I first saw that rule name. I thought "reanalyse: subject wh" should still predict subject gapping.

**Comment by abrsvn** [comment]
Thank you for this. I guess we were thinking about what we were reanalyzing (the initial prediction of subject gap) rather than what we were reanalyzing towards (a non-subject gap). I can't really say which one would be less confusing, but opening this issue here will help either way. Thanks again.
